### ISSUE TITLE
Allocation with pointers to arrays

### ISSUE THREAD

**Issue by mailund** [cmkobel/hmmmlib#12]
https://github.com/cmkobel/hmmmlib/blob/9ca9ef53e9177bc0388140f1e6dc9b5faf95cc5e/hmmmlib/src/Decoding/viterbi.c#L30-L33

It is much more C-like (and much more efficient) to allocate one large chunk of data here. You can easily calculate where each array should start and end in the larger memory chunk. It will also make it easier to mange with respect to deallocation, but you don't have that problem here: you do not deallocate the array but leak memory like crazy if you have large strings as input.

**Comment by cmkobel** [comment]
En-dimensionalitet er indført.
