### ISSUE TITLE
Not necessary to make these global

### ISSUE THREAD

**Issue by mailund** [cmkobel/hmmmlib#13]
https://github.com/cmkobel/hmmmlib/blob/9ca9ef53e9177bc0388140f1e6dc9b5faf95cc5e/hmmmlib/src/Decoding/viterbi.c#L25-L27

It is usually better to define variables for loops in their initialisation. There is nothing wrong with what you are doing, it just looks like old C, where you couldn't define them in the loop-initialisation. Now, it is not the idiom for C.

**Comment by cmkobel** [comment]
Fikset
