### ISSUE TITLE
Brug con. mem i stedet for ** 

### ISSUE THREAD

**Issue by thornado123** [cmkobel/hmmmlib#9]
https://github.com/cmkobel/hmmmlib/blob/9f87a9d41321112170b137324a7cd6c253880191/hmmmlib/src/Decoding/viterbi.c#L31

**Comment by cmkobel** [comment]
Jeg er ikke helt med?

Indtil videre ser linjen således ud:
`double* table = calloc(T*hmm->hiddenStates, sizeof(double*));`

**Comment by mailund** [comment]
Cont er contiguous memory. Lad være med at lave et array af arraysnmen alloker det i en stor block

**Comment by cmkobel** [comment]
Selvfølgelig.
